---
abstract: "Fetch and convert NIST's NVD feeds"
author:
  - 'C.J. Adams-Collier <cjac@f5.com>'
build_requires:
  LWP::UserAgent: 6.04
  Perl::Critic: 1.117
  Test::File: 1.31
  Test::More: 0.98
  Test::Pod: 1.44
  Test::Pod::Coverage: 1.08
  XML::XPath: 1.13
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: NIST-NVD
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 1.20
  DB_File: 1.821
  Data::Dumper: 2.130_02
  IO::Compress::Bzip2: 2.033
  Storable: 2.27
version: 0.10
