---
abstract: 'Placeholder for general NIST::NVD utilities'
author:
  - 'C.J. Adams-Collier <cjac@f5.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: NIST-NVD
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  DB_File: 0
  Data::Dumper: 0
  IO::Compress::Bzip2: 0
  Storable: 0
  Test::File: 0
  Test::More: 0
  XML::XPath: 0
  XML::XPath::XMLParser: 0
version: 0.08
